### ISSUE TITLE
Handling Anon users

### ISSUE THREAD

**Issue by craigmulligan** [resin-io-modules/resin-analytics#12]
I want to use this module for our websites to track page views and other events, but currently `.start()` requires a user obj. 

I'm thinking we generate a uuid if no user object is passed, and then not run the login event. I see a lot methods depend on the properties that are set in the login method like `distinctId` so we will may have to have an alternative like `anonLogin` for add a conditional to the `login` so to not create a new `Person` in mixpanel for every new page visit.  

What do you think? @pimterry @emirotin

**Comment by emirotin** [comment]
Makes sense to have a separate method
In general, mixpanel is already capable of handling anons, we just need to relax the assumptions this module puts on the authentication model.
